# Activity Logs
az policy definition create --name "Activity logs (Administrative) should be exported for retention" --mode All --description "Audit enabling of resource logs. This enables you to recreate activity trails to use for investigation purposes when a security incident occurs or when your network is compromised." --metadata "category=NewCompliance" --rules .\activitylogs-export\rules-admin.json --params .\activitylogs-export\params.json
az policy definition create --name "Activity logs (Security) should be exported for retention" --mode All --description "Audit enabling of resource logs. This enables you to recreate activity trails to use for investigation purposes when a security incident occurs or when your network is compromised." --metadata "category=NewCompliance" --rules .\activitylogs-export\rules-security.json --params .\activitylogs-export\params.json
az policy definition create --name "Activity logs (Alert) should be exported for retention" --mode All --description "Audit enabling of resource logs. This enables you to recreate activity trails to use for investigation purposes when a security incident occurs or when your network is compromised." --metadata "category=NewCompliance" --rules .\activitylogs-export\rules-alert.json --params .\activitylogs-export\params.json
az policy definition create --name "Activity logs (Policy) should be exported for retention" --mode All --description "Audit enabling of resource logs. This enables you to recreate activity trails to use for investigation purposes when a security incident occurs or when your network is compromised." --metadata "category=NewCompliance" --rules .\activitylogs-export\rules-policy.json --params .\activitylogs-export\params.json
az policy assignment create --name "Activity logs (Administrative) should be exported for retention" --policy "Activity logs (Administrative) should be exported for retention"
az policy assignment create --name "Activity logs (Security) should be exported for retention" --policy "Activity logs (Security) should be exported for retention"
az policy assignment create --name "Activity logs (Alert) should be exported for retention" --policy "Activity logs (Alert) should be exported for retention"
az policy assignment create --name "Activity logs (Policy) should be exported for retention" --policy "Activity logs (Policy) should be exported for retention"

# Cosmos
az policy definition create --name "Resource logs (DataPlaneRequests) in CosmosDB should be enabled" --mode All --description "Audit enabling of resource logs. This enables you to recreate activity trails to use for investigation purposes when a security incident occurs or when your network is compromised." --metadata "category=NewCompliance" --rules .\cosmosdb-resourcelogs\rules.json --params .\cosmosdb-resourcelogs\params.json
az policy assignment create --name "Resource logs (DataPlaneRequests) in CosmosDB should be enabled" --policy "Resource logs (DataPlaneRequests) in CosmosDB should be enabled"

# Key Vault
az policy definition create --name "Resource logs in Key Vault should be enabled (AuditEvent)" --mode Indexed --description "Audit enabling of resource logs. This enables you to recreate activity trails to use for investigation purposes when a security incident occurs or when your network is compromised. Edited to ensure AuditEvent is enabled." --metadata "category=NewCompliance" --rules .\keyvault-resourcelogs\rules.json --params .\keyvault-resourcelogs\params.json
az policy assignment create --name "Resource logs in Key Vault should be enabled (AuditEvent)" --policy "Resource logs in Key Vault should be enabled (AuditEvent)"

# Public IP
az policy definition create --name "Resource logs (DDoSNotifications) in Public IP should be enabled" --mode Indexed --description "Audit enabling of resource logs. This enables you to recreate activity trails to use for investigation purposes when a security incident occurs or when your network is compromised." --metadata "category=NewCompliance" --rules .\pubip-resourcelogs\rules-notifications.json --params .\pubip-resourcelogs\params.json
az policy definition create --name "Resource logs (DDoSFlowLogs) in Public IP should be enabled" --mode Indexed --description "Audit enabling of resource logs. This enables you to recreate activity trails to use for investigation purposes when a security incident occurs or when your network is compromised." --metadata "category=NewCompliance" --rules .\pubip-resourcelogs\rules-flow.json --params .\pubip-resourcelogs\params.json
az policy definition create --name "Resource logs (DDoSReports) in Public IP should be enabled" --mode Indexed --description "Audit enabling of resource logs. This enables you to recreate activity trails to use for investigation purposes when a security incident occurs or when your network is compromised." --metadata "category=NewCompliance" --rules .\pubip-resourcelogs\rules-reports.json --params .\pubip-resourcelogs\params.json
az policy assignment create --name "Resource logs (DDoSNotifications) in Public IP should be enabled" --policy "Resource logs (DDoSNotifications) in Public IP should be enabled"
az policy assignment create --name "Resource logs (DDoSFlowLogs) in Public IP should be enabled" --policy "Resource logs (DDoSFlowLogs) in Public IP should be enabled"
az policy assignment create --name "Resource logs (DDoSReports) in Public IP should be enabled" --policy "Resource logs (DDoSReports) in Public IP should be enabled"

# Storage Account
az policy definition create --name "Resource logs (Read) in Storage Account should be enabled" --mode All --description "Audit enabling of resource logs. This enables you to recreate activity trails to use for investigation purposes when a security incident occurs or when your network is compromised." --metadata "category=NewCompliance" --rules .\storageacc-resourcelogs\rules-read.json --params .\storageacc-resourcelogs\params.json
az policy definition create --name "Resource logs (Write) in Storage Account should be enabled" --mode All --description "Audit enabling of resource logs. This enables you to recreate activity trails to use for investigation purposes when a security incident occurs or when your network is compromised." --metadata "category=NewCompliance" --rules .\storageacc-resourcelogs\rules-write.json --params .\storageacc-resourcelogs\params.json
az policy definition create --name "Resource logs (Delete) in Storage Account should be enabled" --mode All --description "Audit enabling of resource logs. This enables you to recreate activity trails to use for investigation purposes when a security incident occurs or when your network is compromised." --metadata "category=NewCompliance" --rules .\storageacc-resourcelogs\rules-delete.json --params .\storageacc-resourcelogs\params.json
az policy assignment create --name "Resource logs (Read) in Storage Account should be enabled" --policy "Resource logs (Read) in Storage Account should be enabled"
az policy assignment create --name "Resource logs (Write) in Storage Account should be enabled" --policy "Resource logs (Write) in Storage Account should be enabled"
az policy assignment create --name "Resource logs (Delete) in Storage Account should be enabled" --policy "Resource logs (Delete) in Storage Account should be enabled"
